use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Read, Write};
use std::path::PathBuf;
use az_logger::info;
use crate::utils::globals::{donut_hasher, gen_seed};
use crate::errors::{DonutError, DonutResult};

/// Generates a list of hashes
///
/// This function accepts a reader object to read the functions, and a path to a file to store the generates hashes at
/// If `opt_seed` is specified, that seed will be used. Otherwise, it'll generate a random seed via [`gen_seed`]
pub fn generate_hashes<R: Read + Sized>(func_list: R, output_path: PathBuf, opt_seed: Option<u32>) -> DonutResult<()> {
    let bufread = BufReader::new(func_list);
    let mut bufwrite = BufWriter::new(File::create(&output_path).map_err(|e| DonutError::Io(e.to_string()))?);
    let comment = format!("// Hashes generated by {} - {}\n", get_package_name(), get_version_str());
    let unused_disable = "#![allow(unused)]\n";
    let seed = if let Some(seed) = opt_seed {
        seed
    } else {
        gen_seed()
    };
    let seed_str = format!("pub const HASH_SEED: u32 = 0x{seed:08x};\n");
    let mut hashes = Vec::new();
    for line in bufread.lines() {
        let line = line.map_err(|e| DonutError::Io(e.to_string()))?;
        info!("Hashing {}", line);
        let fmt = gen_single_hash(&line, seed);
        hashes.push(fmt);
    }
    bufwrite.write(comment.as_bytes()).map_err(|e| DonutError::Io(e.to_string()))?;
    bufwrite.write(unused_disable.as_bytes()).map_err(|e| DonutError::Io(e.to_string()))?;
    bufwrite.write(seed_str.as_bytes()).map_err(|e| DonutError::Io(e.to_string()))?;
    for hash in hashes {
        bufwrite.write(hash.as_bytes()).map_err(|e| DonutError::Io(e.to_string()))?;
    }
    bufwrite.write("\n".as_bytes()).map_err(|e| DonutError::Io(e.to_string()))?;
    Ok(())
}

/// Generates a hash for a given function name
pub fn gen_single_hash(func: &str, seed: u32) -> String {
    let func = func.to_ascii_uppercase();
    let hash =  donut_hasher(&func, seed);
    format!("pub const HASH_{}: u32 = 0x{:08x};\n", func.to_ascii_uppercase().replace(".","_"),hash)
}



fn get_version_str() -> String {
    std::env::var("CARGO_PACKAGE_VERSION").unwrap_or("0.1.0".to_string())
}

fn get_package_name() -> String {
    env!("CARGO_PKG_NAME").to_string()
}